### ISSUE TITLE
Format and ViewFormat Options not working.

### ISSUE THREAD

**Issue by user123x1** [JiriBalcar/angular-datepickr#2]
When trying to set format option as 'MM-DD-YYYY', the default formats seem override.  Maybe hard code.

default:
format: string	format for model value	'DD.MM.YYYY'
viewFormat: string	format for view	'DD.MM.YYYY'

Thanks,

**Comment by JiriBalcar** [comment]
Did you set it as global options or in the template?

**Comment by user123x1** [comment]
Yes, I tried both global and local options. Its seems to be hard code in the following file.
**datepicker-container.component.ts** _(not reading from options)_
example: (several other places within the file)
 

> generateCalendar(..)

  
    let firstDay = moment(`01.${month + 1}.${year}`, 'DD.MM.YYYY'); 

>

**Comment by JiriBalcar** [comment]
Can you try to install version 0.3.4-beta1?

`npm install angular2-datepickr@beta`

Should be fixed.

**Comment by user123x1** [comment]
Yes, the date format options and arrow icons are fixed now at least for the input component. But now we have a new error for the **jb-text-datepicker** component with the following error message:

> error_handler.js:48 EXCEPTION: Error in ./TextDatePickerComponent class TextDatePickerComponent - inline template:1:5 caused by: Cannot read property 'preventDefault' of undefined

>

**Comment by JiriBalcar** [comment]
Should be fixed in 0.3.4-beta3

**Comment by user123x1** [comment]
Looks good! Thank you for a fast response time. :+1:

**Comment by JiriBalcar** [comment]
You are welcome ;-)
