### ISSUE TITLE
Ability to change style.

### ISSUE THREAD

**Issue by user123x1** [JiriBalcar/angular-datepickr#4]
allow ability to change style for the components such as calendar header - background color.  (ViewEncapsulation)

Thanks,

**Comment by JiriBalcar** [comment]
Hi, I would like to leave the ViewEncapsulation.Emulated.

Rigth now you have two options to override styles:

1. **Use global CSS and override the component CSS**
2. **Use "::shadow" or "/deep/" in CSS**

Both with combination with **!important** rule where needed.

**Comment by user123x1** [comment]
Ok thanks.

**Comment by user123x1** [comment]
Can you please provide a code snippet, i am unable to override style. Fyi: I am using angular-cli...

Thanks,
